name: Reusable Deploy
on:
    workflow_call:
        inputs:
            artifact-name:
                description: name of deployable artifact file
                required: false
                default: dist
                type: string

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Get build artifacts
            uses: actions/download-artifact@v3
            with:
              name: ${{inputs.artifact-name}} # dist-files
          - name: List files
            run: ls -lrta
          - name: Deploy
            run: echo "Deploying..."